### ISSUE TITLE
Little line thing

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/nineteen-eighty-five#2]
<img width="758" alt="screen shot 2018-12-05 at 4 14 00 pm" src="https://user-images.githubusercontent.com/158918/49547623-cfd77c00-f8a8-11e8-8124-e32ba19a2e36.png">

That little line thing above all the elements doesn't really fit in anymore. What do you think?

Could we make it more 8 bitty or get rid of it all together?

**Comment by jrtashjian** [comment]
Resolved in: e7e63b7ea8d693b690c331798e6bf4cd06f3a0f8

Made the dash more 8 bitty by setting a 4px width and a 64px length.
