### ISSUE TITLE
Stuttering on hover

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/nineteen-eighty-five#4]
If you hover over the links on my demo site (https://1985.sortabrilliant.com/about/) there seems to be a weird stuttering effect. It's strange and doesn't seem to happen when I use 2019. Maybe something with a transition or something.

**Comment by jrtashjian** [comment]
I can't seem to reproduce this. Can you post a screen capture of the effect? Or if you pull the latest code does this still happen?

**Comment by nickhamze** [comment]
I think I'm working too hard. I can't reproduce it either, maybe I imagined it :) .
