### ISSUE TITLE
Colors don't match

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/nineteen-eighty-five#6]
The accent colors in the customizer don't match the colors on the site.

<img width="1439" alt="screen shot 2018-12-06 at 7 28 35 am" src="https://user-images.githubusercontent.com/158918/49587100-9ba3a000-f928-11e8-9509-84ca73915ce7.png">

<img width="1436" alt="screen shot 2018-12-06 at 7 29 18 am" src="https://user-images.githubusercontent.com/158918/49587122-a9f1bc00-f928-11e8-8f82-05d154ac82ae.png">

**Comment by nickhamze** [comment]
If it's too hard let's just change the default back to the blue and forget about it. I'm not so stuck on this that I want to spend a bunch of time fixing it.

**Comment by jrtashjian** [comment]
I found a few filters I could use in the parent theme which changes the color palette in the customizer. I couldn't change the default blue color but I was able to set it as "custom" and then set the proper HSL values.
